name: Valet+ tests

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

jobs:
  test:
    # Build on Monterey and later Ventura (Not public released yet: https://github.com/actions/runner-images)
    strategy:
      matrix:
        os: [macos-12]
#        php: ['8.2', '8.1', '8.0', '7.4', '7.3', '7.2', '7.1']
        php: ['8.2', '8.1', '7.4']
    runs-on: ${{matrix.os}}
    name: ${{matrix.os}} with ${{matrix.php}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: '[INSTALL] Install PHP 8.0'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL, max_execution_time=-1, memory_limit=512M
          tools: composer:v2
          coverage: none
      - name: '[INSTALL] Composer install'
        run: composer install --no-interaction --prefer-dist
      - name: '[INSTALL] Valet install'
        run: ./valet install

# @todo; add test mailhog.test (should return 200 status code)

      - name: '[TEST] DB commands'
        run: |
          ./valet db create testci | grep "\"testci\" created successfully"
          ./valet db list | grep "testci"
          ./valet db drop testci -y | grep "\"testci\" dropped successfully"

      - name: '[TEST] PHP switch'
        run: |
          ./valet use ${{matrix.php}}
          php -v | grep ${{matrix.php}}
      - name: '[TEST] xdebug on and off'
        run: |
          ./valet xdebug on
          ./valet xdebug off
      - name: '[TEST] memcache on and off'
        run: |
          ./valet memcache on
          ./valet memcache off
